Reporttool
CentralValleyModeling/wrims pull request #81
Opened 2024-03-28 21:15 UTC by hxiedwr

I am merging the ReportTool branch to wrims-devops branch. Please review and approve it.

Please make sure what I am doing is merging ReportTool branch to wrims-devops branch but not the other way around.

2024-03-28 23:23 UTC, rma-tom requested changes

2024-03-28 23:23 UTC, rma-tom commented on wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java
> +		HecTimeSeries htsBase = new HecTimeSeries(scalars.get("FILE_BASE"));
If there's a console output for messages, consider setting the DSS messaging level lower than the default, for example
		HecTimeSeries.setMessageLevel(3);

2024-03-28 23:23 UTC, rma-tom commented on wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java
> +			String data_type = tscBase.type;
TimeSeriesContainer.type is going to give you things like "PER-AVER" or "INST-VAL". You probably want to set your data_type from tscBase.parameter, which is going to be the C-part of the DSS path

2024-03-28 23:39 UTC, hxiedwr commented
Right now, we don’t have console outputs but haven’t got any complaints in the past. So I think this is not urgent.

The same goes to data_type, which is not used to generate tables or charts in the Report Tool.
________________________________
From: Tom Evans ***@***.***>
Sent: Thursday, March 28, 2024 4:23:35 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Xie, ***@***.*** ***@***.***>; Author ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Reporttool (PR #81)


@rma-tom requested changes on this pull request.

________________________________

In wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java<https://github.com/CentralValleyModeling/wrims/pull/81#discussion_r1543826959>:

> @@ -198,12 +196,40 @@ public void doProcessing(IProgressMonitor monitor) {
                monitor.worked(20);

                // open files 1 and file 2 and loop over to plot
-               Group dssGroupBase = Utils.opendss(scalars.get("FILE_BASE"));
-               Group dssGroupAlt = Utils.opendss(scalars.get("FILE_ALT"));
+               HecTimeSeries htsBase = new HecTimeSeries(scalars.get("FILE_BASE"));


If there's a console output for messages, consider setting the DSS messaging level lower than the default, for example
HecTimeSeries.setMessageLevel(3);

________________________________

In wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java<https://github.com/CentralValleyModeling/wrims/pull/81#discussion_r1543830318>:

>                       }
-                       String data_units = Utils.getUnits(refBase, refAlt);
-                       String data_type = Utils.getType(refBase, refAlt);
+                       String data_units = tscBase.units;
+                       String data_type = tscBase.type;


TimeSeriesContainer.type is going to give you things like "PER-AVER" or "INST-VAL". You probably want to set your data_type from tscBase.parameter, which is going to be the C-part of the DSS path

—
Reply to this email directly, view it on GitHub<https://github.com/CentralValleyModeling/wrims/pull/81#pullrequestreview-1967517840>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7C7KVRGN5MGOUXZZRTIQ3Y2SQ7PAVCNFSM6AAAAABFNP3VFCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRXGUYTOOBUGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-28 23:44 UTC, rma-tom commented
When I revised the CalLite report tool, the data_type was used to label the Y axes of the graphs, so I had graphs labeled with "PER-AVER" instead of "STORAGE" for example. If the axis labels in the WRIMS reports don't rely on the variable, then it's not important to make the change I suggested.

2024-03-28 23:51 UTC, rma-tom commented on wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java
> +			String data_type = tscBase.type;
per @hxiedwr "Right now, we don’t have console outputs but haven’t got any complaints in the past. So I think this is not urgent. "

2024-03-28 23:53 UTC, rma-tom commented on wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java
> +			String data_type = tscBase.type;
Sorry -- that last comment belongs in the other location.

2024-03-28 23:53 UTC, rma-tom commented on wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java
> +		HecTimeSeries htsBase = new HecTimeSeries(scalars.get("FILE_BASE"));
per @hxiedwr "Right now, we don’t have console outputs but haven’t got any complaints in the past. So I think this is not urgent. "

2024-03-28 23:56 UTC, rma-tom commented on wrims_v2/wrimsv2_plugin/src/wrimsv2_plugin/reporttool/Report.java
> +			String data_type = tscBase.type;
Per @hxiedwr -- "The same goes to data_type, which is not used to generate tables or charts in the Report Tool."
If this won't cause problems with the labels of the axes, then it's not significant.

2024-03-28 23:57 UTC, hxiedwr commented
Report Tool in WRIMS does not need type information to plot. Especially the type info is not always correct. We use "per-aver" for storage but actually should be "inst-val".

Basically we can think type is a dummy variable.




________________________________
From: Tom Evans ***@***.***>
Sent: Thursday, March 28, 2024 4:44 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Xie, ***@***.*** ***@***.***>; Author ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Reporttool (PR #81)


When I revised the CalLite report tool, the data_type was used to label the Y axes of the graphs, so I had graphs labeled with "PER-AVER" instead of "STORAGE" for example. If the axis labels in the WRIMS reports don't rely on the variable, then it's not important to make the change I suggested.

—
Reply to this email directly, view it on GitHub<https://github.com/CentralValleyModeling/wrims/pull/81#issuecomment-2026326681>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7C7KXWXEPRJIPWRGQRWDLY2STOTAVCNFSM6AAAAABFNP3VFCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRWGMZDMNRYGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-28 23:59 UTC, rma-tom reviewed
Are you able to run this in Eclipse? I tried, but the the re-arrangement of the directories for DevOps broke Eclipse projects. Maybe you can show me how. In code, though, this all looks good.

2024-03-29 00:00 UTC, hxiedwr commented
So in CalLite Report Tool and EPPT, you may want to remove the type info from the axis.
________________________________
From: Xie, ***@***.*** ***@***.***>
Sent: Thursday, March 28, 2024 4:57 PM
To: CentralValleyModeling/wrims ***@***.***>; CentralValleyModeling/wrims ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Reporttool (PR #81)

Report Tool in WRIMS does not need type information to plot. Especially the type info is not always correct. We use "per-aver" for storage but actually should be "inst-val".

Basically we can think type is a dummy variable.




________________________________
From: Tom Evans ***@***.***>
Sent: Thursday, March 28, 2024 4:44 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Xie, ***@***.*** ***@***.***>; Author ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Reporttool (PR #81)


When I revised the CalLite report tool, the data_type was used to label the Y axes of the graphs, so I had graphs labeled with "PER-AVER" instead of "STORAGE" for example. If the axis labels in the WRIMS reports don't rely on the variable, then it's not important to make the change I suggested.

—
Reply to this email directly, view it on GitHub<https://github.com/CentralValleyModeling/wrims/pull/81#issuecomment-2026326681>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7C7KXWXEPRJIPWRGQRWDLY2STOTAVCNFSM6AAAAABFNP3VFCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRWGMZDMNRYGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-29 00:05 UTC, rma-tom approved these changes
I hope that the switch from Vista to HecTimeSeries to read from DSS files will also make the reports run a bit faster.

2024-03-29 00:06 UTC, hxiedwr commented
I am able to run. There is no compilation errors for wrims_plugin, hecdss, and jdiagram projects. The two xtext projects have compilation errors, which are hard to fix (it requires update to newer version of xtext, which may not work with the current code. So don't do it).

Two ways to work around:


  1.
launch the programs by ignoring the compilation errors in xtext projects.
  2.
copy the files under the two xtext projects from the master branch.

If you still have problem, let me know.




________________________________
From: Tom Evans ***@***.***>
Sent: Thursday, March 28, 2024 4:59 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Xie, ***@***.*** ***@***.***>; Mention ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Reporttool (PR #81)


@rma-tom commented on this pull request.

Are you able to run this in Eclipse? I tried, but the the re-arrangement of the directories for DevOps broke Eclipse projects. Maybe you can show me how. In code, though, this all looks good.

—
Reply to this email directly, view it on GitHub<https://github.com/CentralValleyModeling/wrims/pull/81#pullrequestreview-1967574482>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7C7KX5JPOGZWS5P2PHT5TY2SVHDAVCNFSM6AAAAABFNP3VFCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRXGU3TINBYGI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-29 00:11 UTC, rma-tom submitted a review, later dismissed
I submitted an approval, not sure why it's still blocked

2024-03-29 00:40 UTC, hxiedwr commented
Because you were the last developer submitting the code change. GitHub required additional reviewer to approve it.



________________________________
From: Tom Evans ***@***.***>
Sent: Thursday, March 28, 2024 5:11 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Xie, ***@***.*** ***@***.***>; Mention ***@***.***>
Subject: Re: [CentralValleyModeling/wrims] Reporttool (PR #81)


@rma-tom approved this pull request.

I submitted an approval, not sure why it's still blocked

—
Reply to this email directly, view it on GitHub<https://github.com/CentralValleyModeling/wrims/pull/81#pullrequestreview-1967582744>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7C7KQZPAGO3RV5XRNEJTTY2SWTFAVCNFSM6AAAAABFNP3VFCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRXGU4DENZUGQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-29 21:55 UTC, adamkorynta submitted a review, later dismissed
Reviewed Tom's commit (did not review Hao's)

An issue should get created to consolidate this with the callite-report-tool library: https://github.com/CentralValleyModeling/callite-report-tool so that we don't have so much duplicated code.

2024-04-22 17:56 UTC, merged